const BASE_URL = "http://192.168.1.4:5000"
export const USER_URL = BASE_URL + '/api/users/';
export const CUISINE_URL = BASE_URL + '/api/cuisine';
export const ADDRESS_URL = BASE_URL + '/api/users/addaddress/';
export const CHECKOUT_URL = BASE_URL + '/api/checkout/6088240787ea8208fcb85863';
export const COUPON_URL = BASE_URL + '/api/coupon';
export const ORDER_URL = BASE_URL + '/api/orders';
export const MY_ORDER_URL = BASE_URL + '/api/orders/getorderbyuser/';
export const RESTAURANT_URL = BASE_URL + '/api/newrest/active/';
export const CUISINE_TYPE_URL = BASE_URL + '/api/newrest/cuisine_type';
export const MEALS = BASE_URL + '/api/newrest/category/';
export const VEG_NON_VEG = BASE_URL + '/api/newrest/meal_type/';
export const PROFIT_URL = BASE_URL + '/api/plans';
export const CHANGE_ADDRESS_URL = BASE_URL + '/api/users/changeaddress/';
export const GET_PRICE_URL = BASE_URL + '/api/pricing'
export const SLOT_URL = BASE_URL + '/api/slots'